version: '3'
services:
  db:
    image: postgres
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  server:
    image: postgrest/postgrest
    depends_on:
      - db
    ports:
      - "${PGRST_SERVER_PORT}:3000"
    environment:
      PGRST_DB_ANON_ROLE: "anonymous"
      PGRST_DB_URI: "postgres://postgres:postgres@db:5432/postgres"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
      PGRST_RAW_MEDIA_TYPES: "application/xml,text/css,image/jpeg,image/png,text/html"
